site_name: Med-ImageTools Documentation
site_url: https://med-imagetools.readthedocs.io/
nav:
    - Home: index.md
    - AutoPipeline: AutoPipeline.md
    - nnUNet: nnUNet.md

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  
theme: 
    name: material
    features:
    - content.code.annotate