name: publish-pypi

on:
  pull_request:
    types: [closed]

jobs:
  on-success:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install flake8 pytest setuptools wheel twine
          pip install -e .
          pip install -r requirements.txt
      - name: Build binary wheel and a source tarball
        run: |
          python setup.py install
          python setup.py sdist bdist_wheel
      - run: echo 'Tests successful. Publishing to PyPI now.'
      - name: Build app (Ubuntu / macOS)
        env:
          USERNAME: ${{ secrets.pypi_username }}
          KEY: ${{ secrets.pypi_pw }}
        run: python -m twine upload -u $USERNAME -p $KEY dist/*
  on-failure:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'failure' }}
    steps:
      - run: echo 'Tests failed :/ *womp womp*'
