name: publish-pypi

on:
  workflow_run:
    workflows: [main-ci]
    types: [completed]

jobs:
  on-success:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - run: echo 'Tests successful. Publishing to PyPI now.'
      - name: Build app (Ubuntu / macOS)
        env:
          USERNAME: ${{ secrets.pypi_username }}
          KEY: ${{ secrets.pypi_pw }}
        run: python -m twine upload --skip-existing -u $USERNAME -p $KEY dist/*
  on-failure:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'failure' }}
    steps:
      - run: echo 'Tests failed :/ *womp womp*'
